name: Code Quality Checks

on:
  pull_request:
    branches:
      - develop
      - qa
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: pip install pylint

      - name: Run Pylint
        run: pylint AWS/**/*.py
