name: Deploy AWS Resources

on:
  push:
    branches:
      - Child_Branch   # Trigger for dev
      - qa             # Trigger for qa
      - main           # Trigger for master


    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/Child_Branch" ]]; then
            export AWS_ACCOUNT_ID=${{ secrets.DEV_AWS_ACCOUNT_ID }}
            export AWS_REGION=${{ secrets.DEV_AWS_REGION }}
            export S3_BUCKET_NAME=${{ secrets.DEV_S3_BUCKET_NAME }}
            export STACK_NAME=${{ secrets.DEV_STACK_NAME }}
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            export AWS_ACCOUNT_ID=${{ secrets.QA_AWS_ACCOUNT_ID }}
            export AWS_REGION=${{ secrets.QA_AWS_REGION }}
            export S3_BUCKET_NAME=${{ secrets.QA_S3_BUCKET_NAME }}
            export STACK_NAME=${{ secrets.QA_STACK_NAME }}
          else
            export AWS_ACCOUNT_ID=${{ secrets.MASTER_AWS_ACCOUNT_ID }}
            export AWS_REGION=${{ secrets.MASTER_AWS_REGION }}
            export S3_BUCKET_NAME=${{ secrets.MASTER_S3_BUCKET_NAME }}
            export STACK_NAME=${{ secrets.MASTER_STACK_NAME }}
          fi

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file ./Template/${ENVIRONMENT}/${SERVICE}-template.yaml \
            --capabilities CAPABILITY_NAMED_IAM
