jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/Child_Branch" ]]; then
            export STACK_NAME=${{ secrets.DEV_STACK_NAME }}
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            export STACK_NAME=${{ secrets.QA_STACK_NAME }}
          else
            export STACK_NAME=${{ secrets.MASTER_STACK_NAME }}
          fi

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file ./Template/${ENVIRONMENT}/${SERVICE}-template.yaml \
            --capabilities CAPABILITY_NAMED_IAM
