name: Deploy Lambda Function

on:
  push:
    branches:
      - Child_Branch   # Trigger for dev
      - qa             # Trigger for qa
      - main           # Trigger for master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Step 3: Set Environment Variables
      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/Child_Branch" ]]; then
            export ENVIRONMENT="dev"
            export S3_BUCKET_NAME=${{ secrets.DEV_S3_BUCKET_NAME }}
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            export ENVIRONMENT="qa"
            export S3_BUCKET_NAME=${{ secrets.QA_S3_BUCKET_NAME }}
          else
            export ENVIRONMENT="master"
            export S3_BUCKET_NAME=${{ secrets.MASTER_S3_BUCKET_NAME }}
          fi
          echo "Environment: $ENVIRONMENT"
          echo "S3 Bucket Name: $S3_BUCKET_NAME"
          echo "STACK_NAME=lambda-stack-${ENVIRONMENT}" >> $GITHUB_ENV

      # Step 4: Debug Environment
      - name: Debug Environment Variables
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "S3 Bucket Name: $S3_BUCKET_NAME"
          echo "Stack Name: $STACK_NAME"

      # Step 5: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file ./Template/Dev/lambda-template.yml \
            --parameter-overrides Environment=$ENVIRONMENT S3Bucket=$S3_BUCKET_NAME \
            --capabilities CAPABILITY_NAMED_IAM
