name: Deploy Lambda Functions to AWS

on:
  push:
    branches:
      - Dev  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}  

      # Set up Python environment
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Choose the Python version that matches your Lambda runtime

      # Lambda 1 - Install dependencies and deploy
      - name: Install dependencies for Lambda Function 1
        run: |
          cd aws/dev/lambda/Test_lambda1  # Change to the folder for Lambda function 1
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from Lambda function 1's requirements.txt

      # Create deployment package for Lambda Function 1
      - name: Create deployment package for Lambda Function 1
        run: |
          cd aws/dev/lambda/Test_lambda1
          zip -r lambda_function_1.zip .  # Zip all files in the directory

      # Deploy Lambda Function 1
      - name: Deploy Lambda Function 1
        run: |
          aws lambda update-function-code --function-name my-lambda-function-1 --zip-file fileb://aws/dev/lambda/Test_lambda1/lambda_function_1.zip    