# .github/workflows/deploy-dev.yml
name: Deploy to Development Environment

on:
  push:
    branches:
      - develop  # Trigger this workflow on pushes to the 'develop' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy Lambda Function
        run: |
          ./aws/dev/scripts/deploy_lambda.sh  # Script to deploy Lambda function

      - name: Deploy Glue Job
        run: |
          ./aws/dev/scripts/deploy_glue.sh  # Script to deploy Glue job

      - name: Run Athena Query
        run: |
          ./aws/dev/scripts/run_athena_query.sh  # Script to run Athena query
