name: Deploy Lambda Function to AWS

on:
  push:
    branches:
      - Dev  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install Python dependencies

      - name: Deploy Lambda Function (Example)
        run: |
          zip -r lambda_function.zip lambda_function.py  # Adjust based on your setup
          aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://lambda_function.zip


      - name: Create deployment package (zip)
        run: |
          zip -r lambda_function.zip lambda_function.py  # Add lambda_function.py and dependencies to the zip

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://lambda_function.zip
