name: DQ Check for Python Code (Pylint)

on:
  pull_request:
    branches:
      - Dev  # Trigger on PRs to the `Dev` branch, change this as necessary

jobs:
  pylint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the Python version that your Lambda functions use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint check
        run: |
          # Run pylint on the codebase (you can adjust the path to your Lambda folder)
          pylint aws/dev/lambda --disable=R,C --max-line-length=120 --output-format=text > pylint_report.txt || true

      - name: Extract Pylint score and check
        run: |
          # Extract the score from the pylint report
          score=$(tail -n 1 pylint_report.txt | awk '{print $1}')
          echo "Pylint Score: $score"

          # Check if the score is a number and below 10
          if ! [[ "$score" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            echo "Invalid score: $score. Skipping check."
            exit 1
          fi

          # If the score is below 10, fail the workflow
          if [ $(echo "$score < 10" | bc) -eq 1 ]; then
            echo "Pylint score is below 10, failing the workflow."
            exit 1
          fi

      - name: Debug: Print Pylint Report
           run: |
              cat pylint_report.txt
    
